### ISSUE TITLE
reCaptcha - google

### ISSUE THREAD

**Issue by goranapo** [ahornero/clean-login#9]
I just can't make Google recaptcha to work.
Error is "wrong site key" But sitekey is correct, i've generated several, none work.
Lately Google stopped access to V1 of recaptcha, so only V2 and V3 are options.
Are they work with this, because l[atest update for recaptcha](https://github.com/ahornero/clean-login/commit/a59a23021113858db12c175a293a33a9c9c95ef9) is a year ago, so i asume script needs update ??

**Comment by ahornero** [comment]
I didn't receive any comments from other users regarding this issue. Do you have any update or suggested solution? Thanks for reporting it in any case.

**Comment by ahornero** [comment]
[Topic closed due to inactivity]
